[misc]
assume_yes = true
cleanup    = true
disable    = [
  "snap",
  "flatpak",
  "pip3",
  "npm",
  "vim",
  "brew",
]
 
[linux]
arch_package_manager = "pacman"
 
[git]
repos = [
  "~/.zsh/plugins",
]
