[misc]
assume_yes = true
cleanup    = true
disable    = [
  "snap",
  "flatpak",
  "pip3",
  "node",
  "vim",
  "brew_formula",
  "brew_cask",
]
 
[linux]
arch_package_manager = "pacman"
 
[git]
pull_only_repos = [
  "~/.zsh/plugins/fzf-tab",
  "~/.zsh/plugins/zsh-autosuggestions",
  "~/.zsh/plugins/zsh-syntax-highlighting",
]
